/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hr.veleri.projekt.view;

import hr.veleri.projekt.controller.DBspajanje;
import hr.veleri.projekt.model.Mjerenje;
import hr.veleri.projekt.model.Korisnik;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Leon
 */
public class JDialogUnosMjerenja extends javax.swing.JDialog {

    /**
     * Creates new form JDialogUnosMjerenja
     */
    public JDialogUnosMjerenja(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        prikaziKorisnike();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtVisina = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        cmbAktivnost = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtOpsegStruka = new javax.swing.JTextField();
        txtOpsegBokova = new javax.swing.JTextField();
        btnSpremi = new javax.swing.JButton();
        odabirDatuma = new org.jdesktop.swingx.JXDatePicker();
        txtTezina = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableOdabirKorisnika = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnPrikaziMjerenja = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Unos Mjerenja");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("Tjelesna težina (kg):");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText("Tjelesna visina (cm):");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setText("Datum mjerenja:");

        txtVisina.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel19.setText("Dnevna aktivnost:");

        cmbAktivnost.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cmbAktivnost.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Umjerena tjelesna aktivnost", "Normalna tjelesna aktivnost", "Povećana tjelesna aktivnost", "Velika tjelesna aktivnost" }));

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel22.setText("Opseg struka (cm):");

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel23.setText("Opseg bokova (cm):");

        txtOpsegStruka.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        txtOpsegBokova.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        btnSpremi.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnSpremi.setText("Spremi");
        btnSpremi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSpremiActionPerformed(evt);
            }
        });

        odabirDatuma.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        txtTezina.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("Odabir korisnika");
        jPanel1.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        tableOdabirKorisnika.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tableOdabirKorisnika.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Ime", "Prezime", "OIB", "Rođendan", "Spol"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableOdabirKorisnika);
        if (tableOdabirKorisnika.getColumnModel().getColumnCount() > 0) {
            tableOdabirKorisnika.getColumnModel().getColumn(0).setMaxWidth(30);
            tableOdabirKorisnika.getColumnModel().getColumn(4).setMaxWidth(120);
            tableOdabirKorisnika.getColumnModel().getColumn(5).setMaxWidth(90);
        }

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        jLabel3.setMaximumSize(new java.awt.Dimension(123, 82));
        jLabel3.setMinimumSize(new java.awt.Dimension(123, 82));
        jLabel3.setPreferredSize(new java.awt.Dimension(123, 82));
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 90));

        btnPrikaziMjerenja.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnPrikaziMjerenja.setText("Prikaži mjerenja");
        btnPrikaziMjerenja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrikaziMjerenjaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtVisina, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel22)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtOpsegStruka, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jLabel23)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtOpsegBokova, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel7))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(odabirDatuma, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtTezina, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(69, 69, 69)))))
                                .addGap(44, 44, 44))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnSpremi)
                                        .addGap(107, 107, 107)
                                        .addComponent(btnPrikaziMjerenja))
                                    .addComponent(cmbAktivnost, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(odabirDatuma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTezina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel6))
                    .addComponent(txtVisina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel22))
                    .addComponent(txtOpsegStruka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel23))
                    .addComponent(txtOpsegBokova, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbAktivnost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSpremi)
                    .addComponent(btnPrikaziMjerenja))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSpremiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSpremiActionPerformed
        // TODO add your handling code here:
        //ako korisnik nije selektiran onda nedaj da se unos spremi u bazu 
        Mjerenje mjerenje = new Mjerenje();
        int index =tableOdabirKorisnika.getSelectedRow();
        if (index>-1) {
            DefaultTableModel tableModel = (DefaultTableModel)tableOdabirKorisnika.getModel();
            int id = (Integer)tableModel.getValueAt(index, 0);
            
            java.util.Date date;
            java.sql.Date sqldate;
            date = odabirDatuma.getDate();
            sqldate = new java.sql.Date(date.getTime());

            Double tezina = Double.parseDouble(txtTezina.getText());
            Double visina = Double.parseDouble(txtVisina.getText());

            Double opsegStruka = Double.parseDouble(txtOpsegStruka.getText());
            Double opsegBokova = Double.parseDouble(txtOpsegBokova.getText());
            
            String dnevnaAktivnost = (String) cmbAktivnost.getSelectedItem();
                
            mjerenje.setDnevnaAktivnost(dnevnaAktivnost);
            mjerenje.setDatumMjerenja(sqldate);
            mjerenje.setTezina(tezina);
            mjerenje.setVisina(visina);
            mjerenje.setOpsegStruka(opsegStruka);
            mjerenje.setOpsegBokova(opsegBokova);

            DBspajanje.unosMjerenja(mjerenje,id);   
            
            JOptionPane.showMessageDialog(null, "Mjerenje je uneseno",
                        "Unos Mjerenja", JOptionPane.PLAIN_MESSAGE);
            
            txtTezina.setText("");
            txtVisina.setText("");
            txtOpsegStruka.setText("");
            txtOpsegBokova.setText("");

        }
        else {
                JOptionPane.showMessageDialog(null, "Greška kod unosa. "
                        + "Mjerenje nije uneseno!\nKorisnik mora biti selektiran!", "Unos mjerenja",
                    JOptionPane.ERROR_MESSAGE);                
            }
                   
    }//GEN-LAST:event_btnSpremiActionPerformed

    private void btnPrikaziMjerenjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrikaziMjerenjaActionPerformed
        // TODO add your handling code here:
        JDialogPrikazMjerenja dlgPrikaziMjerenja = new JDialogPrikazMjerenja(null,true);
        dlgPrikaziMjerenja.setVisible(true);
    }//GEN-LAST:event_btnPrikaziMjerenjaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogUnosMjerenja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogUnosMjerenja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogUnosMjerenja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogUnosMjerenja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogUnosMjerenja dialog = new JDialogUnosMjerenja(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrikaziMjerenja;
    private javax.swing.JButton btnSpremi;
    private javax.swing.JComboBox<String> cmbAktivnost;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXDatePicker odabirDatuma;
    private javax.swing.JTable tableOdabirKorisnika;
    private javax.swing.JTextField txtOpsegBokova;
    private javax.swing.JTextField txtOpsegStruka;
    private javax.swing.JTextField txtTezina;
    private javax.swing.JTextField txtVisina;
    // End of variables declaration//GEN-END:variables

    private void prikaziKorisnike() {
        DefaultTableModel tableModel = (DefaultTableModel)tableOdabirKorisnika.getModel();
        tableModel.setRowCount(0);
        try {
        ArrayList<Korisnik> listaKorisnika = DBspajanje.ucitajKorisnike();
        for (Korisnik korisnik: listaKorisnika)
            tableModel.addRow(new Object[]{korisnik.getId(),korisnik.getIme(),korisnik.getPrezime(),korisnik.getOib(),
                korisnik.getRodjendan(),korisnik.getSpol()});

        } catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Nema konekcije na bazu. Kontaktirajte administratora."
               ,"Greška kod dohvata korisnika"+ex.toString(), JOptionPane.ERROR_MESSAGE);
        }
    }
}
