/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hr.veleri.projekt.view;

import hr.veleri.projekt.controller.DBspajanje;
import hr.veleri.projekt.model.Korisnik;
import java.time.Instant;
import java.util.Date;
import javax.swing.DefaultListModel;

/**
 *
 * @author Leon
 */
public class JFrameAdmin extends javax.swing.JFrame {

    /**
     * Creates new form JFrameKorisnik
     */
    public JFrameAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenuIzlaz = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuUnosKorisnika = new javax.swing.JMenuItem();
        jMenuPrikazKorisnika = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuUnosMjerenja = new javax.swing.JMenuItem();
        jMenuIzracunMjerenja = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuIzradaJelovnika = new javax.swing.JMenuItem();
        jMenuListaNamirnica = new javax.swing.JMenuItem();
        jMenuItemPrikazJelovnikaKorisnika = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        jLabel4.setMaximumSize(new java.awt.Dimension(123, 82));
        jLabel4.setMinimumSize(new java.awt.Dimension(123, 82));
        jLabel4.setPreferredSize(new java.awt.Dimension(123, 82));

        jMenu4.setText("Datoteka");
        jMenu4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jMenuIzlaz.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jMenuIzlaz.setText("Izlaz");
        jMenuIzlaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuIzlazActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuIzlaz);

        jMenuBar1.add(jMenu4);

        jMenu1.setText("Korisnik");
        jMenu1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jMenuUnosKorisnika.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jMenuUnosKorisnika.setText("Unos");
        jMenuUnosKorisnika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuUnosKorisnikaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuUnosKorisnika);

        jMenuPrikazKorisnika.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jMenuPrikazKorisnika.setText("Prikaz svih korisnika");
        jMenuPrikazKorisnika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPrikazKorisnikaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuPrikazKorisnika);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Mjerenje");
        jMenu2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jMenuUnosMjerenja.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jMenuUnosMjerenja.setText("Unos");
        jMenuUnosMjerenja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuUnosMjerenjaActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuUnosMjerenja);

        jMenuIzracunMjerenja.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jMenuIzracunMjerenja.setText("Izracun");
        jMenuIzracunMjerenja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuIzracunMjerenjaActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuIzracunMjerenja);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Jelovnik");
        jMenu3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jMenuIzradaJelovnika.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jMenuIzradaJelovnika.setText("Izrada");
        jMenuIzradaJelovnika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuIzradaJelovnikaActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuIzradaJelovnika);

        jMenuListaNamirnica.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jMenuListaNamirnica.setText("Namirnice");
        jMenuListaNamirnica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuListaNamirnicaActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuListaNamirnica);

        jMenuItemPrikazJelovnikaKorisnika.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jMenuItemPrikazJelovnikaKorisnika.setText("Prikaz jelovnika korisnika");
        jMenuItemPrikazJelovnikaKorisnika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPrikazJelovnikaKorisnikaActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemPrikazJelovnikaKorisnika);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(147, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuUnosKorisnikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuUnosKorisnikaActionPerformed
        // TODO add your handling code here:
        JDialogUnosKorisnika dlgUnosKorisnika = new JDialogUnosKorisnika(this, true);
        dlgUnosKorisnika.setVisible(true);
    }//GEN-LAST:event_jMenuUnosKorisnikaActionPerformed

    private void jMenuPrikazKorisnikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPrikazKorisnikaActionPerformed
        // TODO add your handling code here:
        JDialogPrikazKorisnika dlgPrikazKorisnika = new JDialogPrikazKorisnika(null,true);
        dlgPrikazKorisnika.setVisible(true);
    }//GEN-LAST:event_jMenuPrikazKorisnikaActionPerformed

    private void jMenuUnosMjerenjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuUnosMjerenjaActionPerformed
        // TODO add your handling code here:
        JDialogUnosMjerenja dlgUnosMjerenja = new JDialogUnosMjerenja(null,true);
        dlgUnosMjerenja.setVisible(true);
    }//GEN-LAST:event_jMenuUnosMjerenjaActionPerformed

    private void jMenuIzracunMjerenjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuIzracunMjerenjaActionPerformed
        // TODO add your handling code here:
        JDialogPrikazMjerenja dlgPrikazMjerenja = new JDialogPrikazMjerenja(null,true);
        dlgPrikazMjerenja.setVisible(true);
    }//GEN-LAST:event_jMenuIzracunMjerenjaActionPerformed

    private void jMenuIzradaJelovnikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuIzradaJelovnikaActionPerformed
        // TODO add your handling code here:
        JDialogOdabirKorisnikaMjerenjaJelovnik dlgIzradaJelovnika = new JDialogOdabirKorisnikaMjerenjaJelovnik(null,true);
        dlgIzradaJelovnika.setVisible(true);
    }//GEN-LAST:event_jMenuIzradaJelovnikaActionPerformed

    private void jMenuIzlazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuIzlazActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuIzlazActionPerformed

    private void jMenuListaNamirnicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuListaNamirnicaActionPerformed
        // TODO add your handling code here:
        JDialogIzmjenaNamirnice dlgIzmjenaNamirnice = new JDialogIzmjenaNamirnice(null,true);
        dlgIzmjenaNamirnice.setVisible(true);
    }//GEN-LAST:event_jMenuListaNamirnicaActionPerformed

    private void jMenuItemPrikazJelovnikaKorisnikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPrikazJelovnikaKorisnikaActionPerformed
        // TODO add your handling code here:
        JDialogPrikazJelovnikaKorisnika dlgPrikazJelovnikaKorisnika = new JDialogPrikazJelovnikaKorisnika(null,true);
        dlgPrikazJelovnikaKorisnika.setVisible(true);
    }//GEN-LAST:event_jMenuItemPrikazJelovnikaKorisnikaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemPrikazJelovnikaKorisnika;
    private javax.swing.JMenuItem jMenuIzlaz;
    private javax.swing.JMenuItem jMenuIzracunMjerenja;
    private javax.swing.JMenuItem jMenuIzradaJelovnika;
    private javax.swing.JMenuItem jMenuListaNamirnica;
    private javax.swing.JMenuItem jMenuPrikazKorisnika;
    private javax.swing.JMenuItem jMenuUnosKorisnika;
    private javax.swing.JMenuItem jMenuUnosMjerenja;
    // End of variables declaration//GEN-END:variables
    DefaultListModel model = new DefaultListModel();
}
